blank_issues_enabled: true
contact_links:
- name: Support Questions
  about: Please use one of our great community resources for support questions!
  url: https://zeek.org/community/
- name: Security Issues
  about: See here for information about how to report security issues.
  url: https://zeek.org/security-reporting/
